version: '3'

services:

    app:
        build: .
        container_name: micro-videos-app
#        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 120s ./.docker/app/entrypoint.sh
#        tty: true
        environment:
            - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
            - GOOGLE_CLOUD_KEY_FILE=${GOOGLE_CLOUD_KEY_FILE}
            - GOOGLE_CLOUD_STORAGE_BUCKET=${GOOGLE_CLOUD_STORAGE_BUCKET}
            - GOOGLE_CLOUD_STORAGE_PATH_PREFIX=${GOOGLE_CLOUD_STORAGE_PATH_PREFIX}
            - GOOGLE_CLOUD_STORAGE_API_URI=${GOOGLE_CLOUD_STORAGE_API_URI}
            - TESTING_PROD=true
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build:  .docker/nginx
        container_name: nginx
#        entrypoint: dockerize -template ./.docker/nginx/nginx_conf.tmpl:/etc/nginx/conf.d/nginx.conf ./.docker/nginx/entrypoint.sh
        environment:
            - SERVICE_NAME=app
            - SERVICE_PORT=9000
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
#            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
