<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Http\Resources\CastMemberResource;
use App\Models\CastMember;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\TestApiResources;
use Tests\Traits\TestValidations;
use Tests\Types\InvalidationTypes;

class CastMemberApiTest extends TestCase
{

    use DatabaseMigrations;

    use TestValidations, TestApiResources;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $castMember = factory(CastMember::class)->create();
        $response = $this->get(route('cast_members.index'));
        $this->assertOk($response, ['data' => [$castMember->toArray()]]);

        $response->assertJsonStructure([
            'data' => [],
            'links' => [],
            'meta' => [],
        ])->assertJson([
            'meta' => ['per_page' => 15]
        ]);
        $resource = CastMemberResource::collection(collect([$castMember]));

        $json = $resource->response();
        $response->assertJson($json->getData(true));
    }

    public function testShow()
    {
        $castMember = factory(CastMember::class)->create();
        $response = $this->get(route('cast_members.show', ['cast_member' => $castMember->id]));
        $this->assertOk($response, ['data' => $castMember->toArray()]);

        $castMember = CastMember::find($response->json('data.id'));
        $this->assertApiResource($response, CastMemberResource::class, $castMember);
    }

    public function testInvalidationData()
    {
        $this->assertInvalidationInStoreAction(route('cast_members.store'), [],[
            new InvalidationTypes('name', 'required')
        ]);

        $this->assertInvalidationInStoreAction(route('cast_members.store'),[
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);

        $castMember = factory(CastMember::class)->create();
        $this->assertInvalidationInUpdateAction(route('cast_members.update', ['cast_member' => $castMember->id]), [
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);
    }

    public function testStore()
    {
        $response = $this->json('POST', route('cast_members.store'), [
            'name' => 'test',
            'type' => 1
        ]);
        $castMember = CastMember::find($response->json('data.id'));
        $this->assertOk($response, ['data' => $castMember->toArray()], 201);
        $this->assertTrue($response->json('data.is_active'));
        $this->assertNull($response->json('data.description'));
        $this->assertApiResource($response, CastMemberResource::class, $castMember);

        $response = $this->json('POST', route('cast_members.store'), [
            'name' => 'test',
            'is_active' => false,
            'type' => 2
        ]);
        $this->assertFalse($response->json('data.is_active'));
        $this->assertEquals(2, $response->json('data.type'));
    }

    public function testUpdate()
    {
        $castMember = factory(CastMember::class)->create([
            'name' => 'creating',
            'type' => 2,
            'is_active' => false,
        ]);
        $response = $this->json('PUT', route('cast_members.update', ['cast_member' => $castMember->id]), [
            'name' => 'updating',
            'type' => 1,
            'is_active' => true,
        ]);
        $castMember = CastMember::find($response->json('data.id'));
        $this->assertOk($response, ['data' => $castMember->toArray()]);
        $response
            ->assertJsonFragment([
                'is_active' => true,
                'type' => 1
            ]);
        $this->assertApiResource($response, CastMemberResource::class, $castMember);
    }

    public function testDelete()
    {
        $castMember = factory(CastMember::class)->create([
            'name' => 'deleting'
        ]);
        $castMember->refresh();
        $id = $castMember->id;
        $response = $this->json('DELETE', route('cast_members.destroy', ['cast_member' => $id]));
        $response->assertStatus(204);
        $this->assertNull(CastMember::find($id));
        $this->assertNotNull(CastMember::withTrashed()->find($id));

        $response = $this->json('DELETE', route('cast_members.destroy', ['cast_member' => $id]));
        $response->assertStatus(404);
    }

}
