<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\CastMember;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\TestValidations;
use Tests\Types\InvalidationTypes;

class CastMemberApiTest extends TestCase
{

    use DatabaseMigrations;

    use TestValidations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $castMember = factory(CastMember::class)->create();
        $response = $this->get(route('cast_members.index'));
        $this->assertOk($response, [$castMember->toArray()]);
    }

    public function testShow()
    {
        $castMember = factory(CastMember::class)->create();
        $response = $this->get(route('cast_members.show', ['cast_member' => $castMember->id]));
        $this->assertOk($response, $castMember->toArray());
    }

    public function testInvalidationData()
    {
        $this->assertInvalidationInStoreAction(route('cast_members.store'), [],[
            new InvalidationTypes('name', 'required')
        ]);

        $this->assertInvalidationInStoreAction(route('cast_members.store'),[
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);

        $castMember = factory(CastMember::class)->create();
        $this->assertInvalidationInUpdateAction(route('cast_members.update', ['cast_member' => $castMember->id]), [
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);
    }

    public function testStore()
    {
        $response = $this->json('POST', route('cast_members.store'), [
            'name' => 'test',
            'type' => 1
        ]);
        $castMember = CastMember::find($response->json('id'));
        $this->assertOk($response, $castMember->toArray(), 201);
        $this->assertTrue($response->json('is_active'));
        $this->assertNull($response->json('description'));

        $response = $this->json('POST', route('cast_members.store'), [
            'name' => 'test',
            'is_active' => false,
            'type' => 2
        ]);
        $this->assertFalse($response->json('is_active'));
        $this->assertEquals(2, $response->json('type'));
    }

    public function testUpdate()
    {
        $castMember = factory(CastMember::class)->create([
            'name' => 'creating',
            'type' => 2,
            'is_active' => false,
        ]);
        $response = $this->json('PUT', route('cast_members.update', ['cast_member' => $castMember->id]), [
            'name' => 'updating',
            'type' => 1,
            'is_active' => true,
        ]);
        $castMember = CastMember::find($response->json('id'));
        $this->assertOk($response, $castMember->toArray());
        $response
            ->assertJsonFragment([
                'is_active' => true,
                'type' => 1
            ]);
    }

    public function testDelete()
    {
        $castMember = factory(CastMember::class)->create([
            'name' => 'deleting'
        ]);
        $castMember->refresh();
        $id = $castMember->id;
        $response = $this->json('DELETE', route('cast_members.destroy', ['cast_member' => $id]));
        $response->assertStatus(204);
        $this->assertNull(CastMember::find($id));
        $this->assertNotNull(CastMember::withTrashed()->find($id));

        $response = $this->json('DELETE', route('cast_members.destroy', ['cast_member' => $id]));
        $response->assertStatus(404);
    }

}
