<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\Category;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Traits\TestValidations;
use Tests\Types\InvalidationTypes;

class CategoryApiTest extends TestCase
{

    use DatabaseMigrations;

    use TestValidations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $category = factory(Category::class)->create();
        $response = $this->get(route('categories.index'));
        $this->assertOk($response, [$category->toArray()]);
    }

    public function testShow()
    {
        $category = factory(Category::class)->create();
        $response = $this->get(route('categories.show', ['category' => $category->id]));
        $this->assertOk($response, $category->toArray());
    }

    public function testInvalidationData()
    {
        $this->assertInvalidationInStoreAction(route('categories.store'), [],[
            new InvalidationTypes('name', 'required')
        ]);

        $this->assertInvalidationInStoreAction(route('categories.store'),[
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);

        $category = factory(Category::class)->create();
        $this->assertInvalidationInUpdateAction(route('categories.update', ['category' => $category->id]), [
            'name' => str_repeat('a', 256),
            'is_active' => 'a'
        ],[
            new InvalidationTypes('name', 'max.string', ['max' => 255]),
            new InvalidationTypes('is_active', 'boolean'),
        ]);
    }

    public function testStore()
    {
        $response = $this->json('POST', route('categories.store'), [
            'name' => 'test 1'
        ]);
        $category = Category::find($response->json('id'));
        $this->assertOk($response, $category->toArray(), 201);
        $this->assertTrue($response->json('is_active'));
        $this->assertNull($response->json('description'));

        $response = $this->json('POST', route('categories.store'), [
            'name' => 'test 2',
            'is_active' => false,
            'description' => 'test'
        ]);
        $this->assertFalse($response->json('is_active'));
        $this->assertEquals('test', $response->json('description'));
    }

    public function testUpdate()
    {
        $category = factory(Category::class)->create([
            'name' => 'creating',
            'is_active' => false,
            'description' => 'creating'
        ]);
        $response = $this->json('PUT', route('categories.update', ['category' => $category->id]), [
            'name' => 'updating',
            'is_active' => true,
            'description' => 'updating'
        ]);
        $category = Category::find($response->json('id'));
        $this->assertOk($response, $category->toArray());
        $response
            ->assertJsonFragment([
                'description' => 'updating',
                'is_active' => true
            ]);
    }

    public function testDelete()
    {
        $category = factory(Category::class)->create([
            'name' => 'deleting'
        ]);
        $category->refresh();
        $id = $category->id;
        $response = $this->json('DELETE', route('categories.destroy', ['category' => $id]));
        $response->assertStatus(204);
        $this->assertNull(Category::find($id));
        $this->assertNotNull(Category::withTrashed()->find($id));

        $response = $this->json('DELETE', route('categories.destroy', ['category' => $id]));
        $response->assertStatus(404);
    }

}
