<?php


namespace Tests\Feature\Models\Video;


use App\Models\Category;
use App\Models\Genre;
use App\Models\Video;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

abstract class BaseVideoTestCase extends TestCase
{

    use DatabaseMigrations;

    protected $videoExample;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $category = factory(Category::class)->create([
            'name' => 'test 1'
        ]);
        $genre = factory(Genre::class)->create([
            'name' => 'test 1'
        ]);
        $genre->categories()->sync([$category->id]);
        $this->videoExample = [
            'title' => 'test',
            'description' => 'test',
            'year_launched' => 2015,
            'rating' => Video::RATING_LIST[0],
            'duration' => 50,
            'opened' => true,
            'categories_id' => [$category->id],
            'genres_id' => [$genre->id],
        ];
    }

}
